language: python 
python: 
- "3.6"
env: 
- DJANGO=2.0 DB=postgres
services:
  - postgresql
addons:
  postgresql: "9.6"
global:
  - PGPORT=5432

before_script:
 - psql -c "create user decide with password 'decide'" 
 - psql -c "create database decidedb owner decide"
 - psql -U postgres -c "ALTER USER decide CREATEDB"

before_install: 
- cd decide
install: 
- pip install -r ../requirements.txt
script: 
- python manage.py test

 if: branch = master 
